// ─────────────────────────────────────────────────────────────────────────
//  GeoPageScan — Audit Engine (server.js)
//  Express API: scrape any URL, check /llms.txt + /robots.txt, then run an
//  AI visibility audit (GEO / AEO / SEO).  When ANTHROPIC_API_KEY is set the
//  audit is generated by Claude; otherwise a built-in heuristic auditor scores
//  the *real* scraped signals and returns the identical JSON schema, so the
//  tool is fully functional with or without an API key.
// ─────────────────────────────────────────────────────────────────────────

import express from "express";
import cors from "cors";
import * as cheerio from "cheerio";
import fetch from "node-fetch";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { timingSafeEqual } from "node:crypto";
import "dotenv/config";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PORT = process.env.PORT || 3001;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY || "";
// Default to Sonnet: ~5x cheaper and ~2x faster than Opus for the public tool.
// Override per-environment with ANTHROPIC_MODEL (e.g. claude-opus-4-5 for max quality).
const ANTHROPIC_MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";
// Shared secret for the internal server-to-server audit API (e.g. Pulsec).
const INTERNAL_API_KEY = process.env.INTERNAL_API_KEY || "";
const USER_AGENT =
  "GeoPageScan/1.0 (AI visibility audit; hello@geopagescan.com)";

const app = express();
app.set("trust proxy", true); // behind Railway's proxy — derive real client IP from X-Forwarded-For
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// Public free tool: max scans per IP per day (heuristic engine, no cost).
const PUBLIC_SCAN_LIMIT = Number(process.env.PUBLIC_SCAN_LIMIT) || 5;

// Load the living config (weights, crawler list, schema impacts).
let CONFIG = {};
try {
  CONFIG = JSON.parse(await readFile(join(__dirname, "audit-config.json"), "utf8"));
} catch {
  CONFIG = {};
}

const AI_CRAWLERS = (CONFIG.aiCrawlers || []).map((c) => c.name);
const CATEGORY_WEIGHTS = CONFIG.categoryWeights || {
  content: 0.22,
  "structured-data": 0.2,
  crawlability: 0.18,
  llms: 0.16,
  authority: 0.14,
  technical: 0.1,
};

// ── small helpers ─────────────────────────────────────────────────────────
const clamp = (n) => Math.max(0, Math.min(100, Math.round(n)));

function normalizeUrl(input) {
  let url = (input || "").trim();
  if (!url) { const e = new Error("URL is required"); e.status = 400; throw e; }
  if (!/^https?:\/\//i.test(url)) url = "https://" + url;
  let u;
  try { u = new URL(url); } catch { const e = new Error("Invalid URL"); e.status = 400; throw e; }
  return { href: u.href, origin: u.origin, host: u.hostname };
}

async function fetchWithTimeout(url, opts = {}, ms = 8000) {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(url, {
      ...opts,
      redirect: "follow",
      signal: controller.signal,
      headers: { "User-Agent": USER_AGENT, ...(opts.headers || {}) },
    });
  } finally {
    clearTimeout(t);
  }
}

// ── Task 1: scrape the target URL ──────────────────────────────────────────
async function scrapeUrl(href) {
  const res = await fetchWithTimeout(href, {}, 15000);
  if (!res.ok) throw new Error(`Target responded ${res.status} ${res.statusText}`);
  const html = await res.text();
  const $ = cheerio.load(html);

  const attr = (sel, a) => ($(sel).attr(a) || "").trim();
  const metaName = (n) => attr(`meta[name="${n}"]`, "content");
  const metaProp = (p) => attr(`meta[property="${p}"]`, "content");

  // JSON-LD blocks
  const jsonLd = [];
  const schemaTypes = new Set();
  $('script[type="application/ld+json"]').each((_, el) => {
    const raw = $(el).contents().text();
    jsonLd.push(raw.slice(0, 6000));
    try {
      const parsed = JSON.parse(raw);
      const collect = (node) => {
        if (!node || typeof node !== "object") return;
        if (Array.isArray(node)) return node.forEach(collect);
        if (node["@type"]) {
          [].concat(node["@type"]).forEach((t) => schemaTypes.add(String(t)));
        }
        // recurse into every nested object/array so nested types (AggregateRating,
        // Person/founder, ContactPoint, @graph, etc.) are also detected
        for (const k in node) {
          if (node[k] && typeof node[k] === "object") collect(node[k]);
        }
      };
      collect(parsed);
    } catch {
      /* malformed JSON-LD — still counts as "present" via jsonLd array */
    }
  });

  const h1s = $("h1").map((_, e) => $(e).text().trim()).get().filter(Boolean).slice(0, 5);
  const h2s = $("h2").map((_, e) => $(e).text().trim()).get().filter(Boolean).slice(0, 10);
  const h3s = $("h3").map((_, e) => $(e).text().trim()).get().filter(Boolean).slice(0, 10);

  // body text without scripts/styles/nav/footer
  const $body = cheerio.load(html);
  $body("script, style, noscript, nav, footer, header, svg").remove();
  const bodyText = $body("body").text().replace(/\s+/g, " ").trim();

  return {
    finalUrl: res.url || href,
    statusCode: res.status,
    title: $("title").first().text().trim(),
    metaDescription: metaName("description"),
    canonical: attr('link[rel="canonical"]', "href"),
    metaRobots: metaName("robots"),
    viewport: metaName("viewport"),
    author: metaName("author"),
    lang: attr("html", "lang"),
    og: {
      title: metaProp("og:title"),
      description: metaProp("og:description"),
      image: metaProp("og:image"),
      type: metaProp("og:type"),
      siteName: metaProp("og:site_name"),
    },
    twitterCard: metaName("twitter:card"),
    hreflangCount: $('link[rel="alternate"][hreflang]').length,
    jsonLdCount: jsonLd.length,
    schemaTypes: [...schemaTypes],
    jsonLd,
    h1s,
    h2s,
    h3s,
    headingCount: $("h1,h2,h3,h4").length,
    wordCount: bodyText ? bodyText.split(/\s+/).length : 0,
    imagesMissingAlt: $("img").filter((_, e) => !$(e).attr("alt")).length,
    bodyText: bodyText.slice(0, 4000),
  };
}

// ── Task 2: /llms.txt ──────────────────────────────────────────────────────
async function checkLlmsTxt(origin) {
  try {
    const res = await fetchWithTimeout(`${origin}/llms.txt`, {}, 5000);
    if (!res.ok) return { exists: false, content: "" };
    const text = await res.text();
    // Guard: some servers return an HTML 404 page with 200.
    if (/<html/i.test(text.slice(0, 200))) return { exists: false, content: "" };
    return { exists: true, content: text.slice(0, 2000), length: text.length };
  } catch {
    return { exists: false, content: "" };
  }
}

// ── Task 3: /robots.txt ────────────────────────────────────────────────────
async function checkRobots(origin) {
  try {
    const res = await fetchWithTimeout(`${origin}/robots.txt`, {}, 5000);
    if (!res.ok) return { exists: false, content: "", aiBotsAllowed: [], aiBotsBlocked: [], sitemap: false };
    const text = await res.text();
    if (/<html/i.test(text.slice(0, 200)))
      return { exists: false, content: "", aiBotsAllowed: [], aiBotsBlocked: [], sitemap: false };

    const lower = text.toLowerCase();
    const mentioned = AI_CRAWLERS.filter((b) => lower.includes(b.toLowerCase()));
    // crude allow/block detection per mentioned bot
    const blocked = [];
    const allowed = [];
    for (const bot of mentioned) {
      const re = new RegExp(`user-agent:\\s*${bot}[\\s\\S]*?(?=user-agent:|$)`, "i");
      const block = (text.match(re) || [""])[0].toLowerCase();
      if (/disallow:\s*\/\s*(\n|$)/.test(block)) blocked.push(bot);
      else allowed.push(bot);
    }
    return {
      exists: true,
      content: text.slice(0, 1000),
      mentionsAiBots: mentioned,
      aiBotsAllowed: allowed,
      aiBotsBlocked: blocked,
      sitemap: /sitemap:/i.test(text),
    };
  } catch {
    return { exists: false, content: "", aiBotsAllowed: [], aiBotsBlocked: [], sitemap: false };
  }
}

// ── The expert audit system prompt (used when Claude API is available) ──────
const SYSTEM_PROMPT = `You are GeoPageScan, an expert auditor for AI search visibility (GEO, AEO, SEO). You receive data scraped from a page plus its /llms.txt and /robots.txt.

Audit it across EXACTLY six categories, using these exact ids:
- llms: llms.txt presence, entity clarity, FAQ for AI Q&A
- structured-data: JSON-LD and Schema.org types
- crawlability: robots.txt AI-bot access, sitemap, JS/video content barriers
- authority: author/founder linking, review schema, About quality
- content: direct-answer structure, Q&A headings, informational vs promotional
- technical: canonical, hreflang, Open Graph, viewport, Core Web Vitals

Score 0-100 per category and overall (>=70 good, 40-69 needs work, <40 poor). Reward real evidence, penalize gaps; every issue needs a concrete, actionable fix.

Return ONLY this JSON object (no prose, no markdown code fences):
{"siteName":"string","siteDescription":"one sentence","overallScore":0,"scoreBreakdown":{"contentClarity":0,"structuredData":0,"aiCrawlability":0,"authoritySignals":0,"llmsTxt":0},"categories":[{"id":"llms","title":"string","priority":"critical|high|medium|low","score":0,"summary":"one sentence","items":[{"issue":"string","impact":"string","fix":"string","effort":"easy|medium|hard"}]}],"quickWins":["string"],"topRecommendation":"string"}

All six ids are required. Be COMPACT and fast: at most 2 items per category (most important first); one short sentence for each issue/impact/fix/summary; at most 5 quickWins.`;

// Send Claude a slimmed payload — drop the raw JSON-LD blocks (huge on real sites;
// schemaTypes + count carry the signal) and cap body text — to keep it fast.
function buildUserPrompt(data) {
  const s = data.scrape || {};
  const slim = {
    url: data.url,
    host: data.host,
    page: {
      title: s.title, metaDescription: s.metaDescription, canonical: s.canonical, metaRobots: s.metaRobots,
      viewport: s.viewport, lang: s.lang, author: s.author, og: s.og, twitterCard: s.twitterCard,
      hreflangCount: s.hreflangCount, jsonLdCount: s.jsonLdCount, schemaTypes: s.schemaTypes,
      h1s: s.h1s, h2s: s.h2s, h3s: s.h3s, headingCount: s.headingCount,
      wordCount: s.wordCount, imagesMissingAlt: s.imagesMissingAlt,
      bodyText: (s.bodyText || "").slice(0, 2500),
    },
    llmsTxt: { exists: data.llms?.exists, content: (data.llms?.content || "").slice(0, 500) },
    robots: {
      exists: data.robots?.exists, sitemap: data.robots?.sitemap,
      aiBotsAllowed: data.robots?.aiBotsAllowed, aiBotsBlocked: data.robots?.aiBotsBlocked,
    },
  };
  return `Scraped data:\n${JSON.stringify(slim)}\n\nReturn ONLY the JSON report.`;
}

// Robustly parse the audit JSON from Claude's text: strip markdown fences,
// isolate the JSON object, and — if the response was truncated — repair it by
// trimming to the last complete structure and closing open brackets.
function parseAuditJson(raw) {
  let text = (raw || "").trim();
  // strip ```json ... ``` / ``` ... ``` fences if present
  text = text.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "").trim();
  const start = text.indexOf("{");
  if (start === -1) throw new Error("Claude did not return JSON");
  const body = text.slice(start);

  // 1) fast path: trim to the last '}' and parse as-is
  const lastBrace = body.lastIndexOf("}");
  if (lastBrace !== -1) {
    try { return JSON.parse(body.slice(0, lastBrace + 1)); } catch { /* fall through to repair */ }
  }

  // 2) truncation repair: walk the string tracking string-state + bracket depth,
  //    cut at the last closed bracket, then append the still-open closers.
  let inStr = false, esc = false;
  const stack = [];       // expected closing chars, in open order
  let cut = -1, cutStack = "";
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "{" || c === "[") stack.push(c === "{" ? "}" : "]");
    else if (c === "}" || c === "]") { stack.pop(); cut = i; cutStack = stack.join(""); }
  }
  if (cut === -1) throw new Error("Claude JSON is unrepairable (no complete structure)");
  const repaired = body.slice(0, cut + 1).replace(/,\s*$/, "") + cutStack.split("").reverse().join("");
  return JSON.parse(repaired);
}

// ── Call Claude ─────────────────────────────────────────────────────────────
async function callClaude(data) {
  const res = await fetchWithTimeout(
    "https://api.anthropic.com/v1/messages",
    {
      method: "POST",
      headers: {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: ANTHROPIC_MODEL,
        max_tokens: 8192, // headroom so the ~5k-token report is never truncated
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: buildUserPrompt(data) }],
      }),
    },
    28000 // hard timeout: abort + fall back to heuristic rather than ever hang
  );

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Claude API ${res.status}: ${errText.slice(0, 300)}`);
  }
  const json = await res.json();
  const text = (json.content || []).map((b) => b.text || "").join("");
  if (json.stop_reason === "max_tokens") {
    console.warn("[audit] Claude hit max_tokens — parsing with truncation repair");
  }
  return parseAuditJson(text);
}

// ── Heuristic auditor (no API key required) ─────────────────────────────────
// Scores the REAL scraped signals. Returns the identical JSON schema.
function heuristicAudit({ scrape, llms, robots, host }) {
  const text = (scrape.bodyText || "").toLowerCase();
  const headings = [...scrape.h1s, ...scrape.h2s, ...scrape.h3s].join(" ").toLowerCase();
  const has = (arr, kw) => arr.some((t) => String(t).toLowerCase().includes(kw));

  const siteName =
    scrape.og.siteName ||
    (scrape.title || "").split(/[|\-–—:]/)[0].trim() ||
    host;
  const siteDescription =
    scrape.metaDescription ||
    scrape.og.description ||
    (scrape.bodyText || "").slice(0, 140).trim() ||
    `${siteName} website.`;

  // signal detections
  const qWords = /\b(what|how|why|when|where|who|which|is|are|can|should|do|does)\b/;
  const questionHeadings = [...scrape.h2s, ...scrape.h3s].filter((h) => qWords.test(h.toLowerCase())).length;
  const hasFaqHeading = has(scrape.h2s, "faq") || has(scrape.h2s, "frequently asked") || headings.includes("question");
  const promo = ["best", "leading", "world-class", "#1", "number one", "trusted", "award-winning", "cutting-edge", "innovative", "premier"];
  const promoHits = promo.filter((w) => text.includes(w)).length;
  const hasDefinition = / is (a|an|the) /.test(text);
  const schemaSet = new Set(scrape.schemaTypes.map((s) => s.toLowerCase()));
  const hasType = (t) => schemaSet.has(t.toLowerCase());

  const cats = [];
  const push = (id, title, score, priority, summary, items) =>
    cats.push({ id, title, score: clamp(score), priority, summary, items });

  // 1) LLM Optimization ─────────────────────────────────────────────
  {
    let s = 5;
    const items = [];
    if (llms.exists) {
      s += 55;
      const lc = (llms.content || "").toLowerCase();
      if (lc.length > 200) s += 10;
      if (/contact|email|@/.test(lc)) s += 5; else items.push({ issue: "llms.txt has no contact info", impact: "AI assistants can't surface a way to reach you.", fix: "Add a Contact section with email and key URLs to /llms.txt.", effort: "easy" });
      if (/service|product|offer/.test(lc)) s += 5; else items.push({ issue: "llms.txt missing a services/products list", impact: "AI can't enumerate what you do.", fix: "List your core services/products with one-line descriptions in /llms.txt.", effort: "easy" });
    } else {
      items.push({ issue: "No /llms.txt file found", impact: "AI assistants have no structured entry point describing your entity, services and key pages — the single highest-impact GEO gap.", fix: "Create /llms.txt at your domain root with: a one-paragraph overview, founding year, a services list, key page URLs, target audience and contact info.", effort: "easy" });
    }
    if (!hasFaqHeading) {
      items.push({ issue: "No FAQ / Q&A content detected", impact: "FAQ blocks are the content AI engines quote most often for question queries.", fix: "Add a FAQ section answering the top 6-8 questions customers ask, each as a question heading with a direct one-paragraph answer.", effort: "medium" });
    } else s += 10;
    if (!hasDefinition) {
      items.push({ issue: "No clear entity definition sentence", impact: "AI needs a plain 'X is a …' sentence to define who you are.", fix: "Open your homepage/About with a sentence like '<Company> is a <category> that <does what> for <audience>.'", effort: "easy" });
    } else s += 5;
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "low";
    push("llms", "LLM Optimization", s, priority,
      llms.exists ? "An llms.txt file exists — refine it so AI engines get a complete, current entity summary." : "No llms.txt and thin Q&A structure — AI engines lack a clean entry point to understand and cite you.",
      items.length ? items : [{ issue: "Minor: keep llms.txt current", impact: "Stale entity data leads to outdated AI answers.", fix: "Review /llms.txt quarterly for new services and pages.", effort: "easy" }]);
  }

  // 2) Structured Data & Schema ─────────────────────────────────────
  {
    let s = 10;
    const items = [];
    if (scrape.jsonLdCount > 0) {
      s += 33;
      const valuable = ["FAQPage", "LocalBusiness", "Organization", "Article", "BlogPosting", "HowTo", "AggregateRating", "Product", "Review", "BreadcrumbList", "WebSite", "WebApplication", "Person"];
      const present = valuable.filter(hasType);
      s += Math.min(45, present.length * 8);
      if (hasType("FAQPage") && (hasType("Organization") || hasType("LocalBusiness"))) s += 7;
      if (!hasType("Organization") && !hasType("LocalBusiness"))
        items.push({ issue: "No Organization / LocalBusiness schema", impact: "AI can't resolve your brand as a knowledge-graph entity.", fix: "Add Organization (or LocalBusiness for a local company) JSON-LD with name, url, logo, sameAs and contact.", effort: "medium" });
      if (!hasType("FAQPage"))
        items.push({ issue: "No FAQPage schema", impact: "FAQPage markup is the most directly quoted schema in AI answers.", fix: "Wrap your FAQ in FAQPage JSON-LD with Question/Answer pairs matching the visible content.", effort: "medium" });
      if (!hasType("AggregateRating") && !hasType("Review"))
        items.push({ issue: "No Review / AggregateRating schema", impact: "Star ratings are surfaced by AI in business recommendations.", fix: "Add AggregateRating JSON-LD for your existing reviews (ratingValue, reviewCount).", effort: "medium" });
      if (present.length)
        items.unshift({ issue: `Detected schema: ${present.join(", ")}`, impact: "Good — these entity signals are machine-readable. Expand coverage to capture more AI surfaces.", fix: "Add any missing high-impact types (FAQPage, AggregateRating, HowTo) relevant to your content.", effort: "medium" });
    } else {
      items.push({ issue: "No JSON-LD structured data found", impact: "Without Schema.org markup, AI engines must guess your entity, offerings and trust signals — they usually skip you.", fix: "Add JSON-LD for Organization/LocalBusiness, plus FAQPage and AggregateRating where relevant. Validate in Google Rich Results Test.", effort: "medium" });
    }
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "medium";
    push("structured-data", "Structured Data & Schema", s, priority,
      scrape.jsonLdCount > 0 ? `${scrape.jsonLdCount} JSON-LD block(s) found — broaden Schema.org coverage for AI extraction.` : "No structured data — the largest machine-readability gap on the page.",
      items);
  }

  // 3) AI Crawlability ──────────────────────────────────────────────
  {
    let s = 30;
    const items = [];
    if (robots.exists) {
      s += 15;
      if (robots.sitemap) s += 10; else items.push({ issue: "robots.txt has no Sitemap directive", impact: "Crawlers (AI included) discover pages slower without a sitemap pointer.", fix: "Add 'Sitemap: https://" + host + "/sitemap.xml' to robots.txt.", effort: "easy" });
      const allowed = robots.aiBotsAllowed || [];
      const blocked = robots.aiBotsBlocked || [];
      if (blocked.length) {
        s -= 20;
        items.push({ issue: `AI crawlers blocked in robots.txt: ${blocked.join(", ")}`, impact: "Blocked bots can never cite you — this makes you invisible to those engines.", fix: "Change Disallow to Allow for AI user-agents you want citing you (GPTBot, ClaudeBot, PerplexityBot, Google-Extended).", effort: "easy" });
      }
      if (allowed.length >= 3) s += 25;
      else items.push({ issue: "AI bots not explicitly allowed", impact: "Default rules are ambiguous; explicit Allow rules signal intent and improve coverage.", fix: "Add explicit 'User-agent: GPTBot / Allow: /' blocks for GPTBot, ChatGPT-User, ClaudeBot, PerplexityBot, Google-Extended.", effort: "easy" });
    } else {
      items.push({ issue: "No robots.txt found", impact: "AI crawlers have no explicit access rules and may crawl conservatively or not at all.", fix: "Publish /robots.txt that allows the major AI user-agents and links your sitemap.", effort: "easy" });
    }
    // JS / content barriers
    if (scrape.wordCount < 250) {
      s -= 15;
      items.push({ issue: `Very little crawlable text (${scrape.wordCount} words)`, impact: "If the hero is video/JS-rendered, AI crawlers see almost no content above the fold.", fix: "Ensure key messaging exists as real HTML text (not only inside video, images or client-rendered JS).", effort: "medium" });
    } else s += 10;
    if (scrape.imagesMissingAlt > 4)
      items.push({ issue: `${scrape.imagesMissingAlt} images missing alt text`, impact: "Alt text is one of the few ways crawlers read image content.", fix: "Add descriptive alt attributes to meaningful images.", effort: "easy" });
    if (llms.exists) s += 5; // an llms.txt is itself a strong AI-crawl-friendliness signal
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "medium";
    push("crawlability", "AI Crawlability", s, priority,
      robots.exists ? "robots.txt exists — make AI-bot access explicit and remove any content barriers." : "No robots.txt — AI bot access is undefined.",
      items.length ? items : [{ issue: "Crawlability looks healthy", impact: "AI bots can reach your content.", fix: "Keep robots.txt and sitemap current as you add sections.", effort: "easy" }]);
  }

  // 4) Authority Signals ────────────────────────────────────────────
  {
    let s = 25;
    const items = [];
    const sameAs = scrape.jsonLd.join(" ").toLowerCase().includes("sameas");
    if (sameAs) s += 20; else items.push({ issue: "No sameAs entity links", impact: "AI builds trust by cross-referencing your brand on LinkedIn, Wikidata, Crunchbase.", fix: "Add a sameAs array in Organization JSON-LD linking your official profiles.", effort: "medium" });
    if (scrape.author || has(scrape.h2s, "about") || text.includes("founded") || text.includes("our team")) s += 20;
    else items.push({ issue: "Weak author / founder entity signals", impact: "Editorial and brand authority depend on named, linkable people.", fix: "Add an About section naming founders/authors and link them to LinkedIn / Person schema.", effort: "medium" });
    if (hasType("AggregateRating") || hasType("Review") || text.includes("review") || text.includes("testimonial")) s += 15;
    else items.push({ issue: "No visible reviews or testimonials", impact: "Social proof is a strong AI recommendation signal.", fix: "Surface customer reviews/testimonials and mark them up with Review/AggregateRating schema.", effort: "medium" });
    if (text.includes("about")) s += 5;
    if (hasType("Organization") || hasType("LocalBusiness")) s += 6; // machine-readable brand entity
    if (hasType("AggregateRating") || hasType("Review")) s += 4;    // machine-readable trust signal
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "medium";
    push("authority", "Authority Signals", s, priority,
      "Entity authority comes from named people, external profile links and machine-readable trust signals.",
      items.length ? items : [{ issue: "Authority signals present", impact: "You have trust signals AI can use.", fix: "Reinforce them with sameAs links and Review schema.", effort: "medium" }]);
  }

  // 5) Content Clarity ──────────────────────────────────────────────
  {
    let s = 35;
    const items = [];
    if (questionHeadings >= 2) s += 20; else items.push({ issue: "Few question-style headings", impact: "AI extracts answers best from 'What/How/Why' headings followed by direct answers.", fix: "Reframe section headings as the questions your audience asks, and answer them in the first sentence.", effort: "medium" });
    if (hasDefinition) s += 10; else items.push({ issue: "No direct-answer / definition sentences", impact: "Generative engines prefer content that states facts plainly up front.", fix: "Lead key sections with a one-sentence direct answer before elaborating.", effort: "medium" });
    if (scrape.wordCount > 600) s += 15; else if (scrape.wordCount < 250) items.push({ issue: "Thin page content", impact: "There isn't enough substantive text for AI to summarize or cite.", fix: "Expand with informational content: explanations, comparisons, FAQs, specifics.", effort: "medium" });
    if (promoHits >= 4) { s -= 15; items.push({ issue: `Promotional tone (${promoHits} marketing superlatives)`, impact: "AI engines favor informational, factual content over sales language.", fix: "Replace superlatives with concrete facts, numbers, named outcomes and specifics.", effort: "medium" }); }
    else s += 10;
    if (scrape.headingCount >= 5) s += 5; else items.push({ issue: "Sparse heading structure", impact: "Without clear headings, content is a wall of text AI struggles to parse.", fix: "Break content into clearly-titled sections with a logical H1→H2→H3 hierarchy.", effort: "easy" });
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "medium";
    push("content", "Content Clarity", s, priority,
      "Clarity for AI = question-led headings, direct answers, informational depth and minimal hype.",
      items.length ? items : [{ issue: "Content structure is solid", impact: "AI can parse and quote your content.", fix: "Keep adding question-led sections as you publish.", effort: "easy" }]);
  }

  // 6) Technical SEO ────────────────────────────────────────────────
  {
    let s = 30;
    const items = [];
    if (scrape.title) s += 10; else items.push({ issue: "Missing <title>", impact: "Title is a primary relevance and entity signal.", fix: "Add a descriptive, keyword-aware <title> (~50-60 chars).", effort: "easy" });
    if (scrape.metaDescription) s += 10; else items.push({ issue: "Missing meta description", impact: "Used as a summary by search and some AI surfaces.", fix: "Add a 140-160 char meta description summarizing the page.", effort: "easy" });
    if (scrape.canonical) s += 8; else items.push({ issue: "No canonical tag", impact: "Duplicate-URL ambiguity dilutes entity signals.", fix: "Add <link rel=\"canonical\"> pointing to the preferred URL.", effort: "easy" });
    if (scrape.viewport) s += 7; else items.push({ issue: "No viewport meta", impact: "Mobile usability is a ranking and UX signal.", fix: "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.", effort: "easy" });
    if (scrape.og.title || scrape.og.image) s += 10; else items.push({ issue: "Incomplete Open Graph tags", impact: "Weak link previews reduce shares and social/AI context.", fix: "Add og:title, og:description and a 1200×630 og:image.", effort: "easy" });
    if (scrape.hreflangCount > 0) s += 10; else if (/\.co\.|\/(en|he|fr|de|es)\//.test(scrape.finalUrl)) items.push({ issue: "No hreflang tags", impact: "Multilingual/multi-region pages aren't connected for AI or search.", fix: "Add hreflang link tags linking each language/region variant.", effort: "medium" });
    if (scrape.lang) s += 5; else items.push({ issue: "No <html lang> attribute", impact: "Language detection helps AI summarize correctly.", fix: "Set <html lang=\"…\"> to the page's primary language.", effort: "easy" });
    const priority = s < 40 ? "critical" : s < 70 ? "high" : "medium";
    push("technical", "Technical SEO", s, priority,
      "Core technical signals are the foundation both classic search and AI engines still rely on.",
      items.length ? items : [{ issue: "Technical foundations are solid", impact: "Crawlers get clean signals.", fix: "Monitor Core Web Vitals and keep metadata current.", effort: "easy" }]);
  }

  // overall = weighted blend
  const overall = clamp(
    cats.reduce((sum, c) => sum + c.score * (CATEGORY_WEIGHTS[c.id] || 1 / cats.length), 0)
  );

  // map to scoreBreakdown
  const byId = Object.fromEntries(cats.map((c) => [c.id, c.score]));
  const scoreBreakdown = {
    contentClarity: byId["content"],
    structuredData: byId["structured-data"],
    aiCrawlability: byId["crawlability"],
    authoritySignals: byId["authority"],
    llmsTxt: byId["llms"],
  };

  // quick wins = easy fixes from the lowest-scoring categories first
  const quickWins = [];
  [...cats].sort((a, b) => a.score - b.score).forEach((c) => {
    c.items.filter((i) => i.effort === "easy").forEach((i) => {
      if (quickWins.length < 6 && !/^Detected schema|present|solid|healthy|Minor/i.test(i.issue))
        quickWins.push(i.fix);
    });
  });
  if (!quickWins.length) quickWins.push("Keep your llms.txt, schema and robots.txt current as the AI search landscape evolves.");

  const worst = [...cats].sort((a, b) => a.score - b.score)[0];
  const topRecommendation =
    worst.score < 40
      ? `Start with ${worst.title}: ${worst.items[0]?.fix || worst.summary}`
      : `Solid foundation. Biggest remaining gain is in ${worst.title} — ${worst.items[0]?.fix || worst.summary}`;

  return {
    siteName,
    siteDescription,
    overallScore: overall,
    scoreBreakdown,
    categories: cats,
    quickWins: quickWins.slice(0, 6),
    topRecommendation,
    engine: "heuristic",
  };
}

// ── Validate / normalize an audit object to the strict schema ───────────────
const REQUIRED_IDS = ["llms", "structured-data", "crawlability", "authority", "content", "technical"];
function ensureSchema(audit) {
  if (!audit || typeof audit !== "object") throw new Error("Audit is not an object");
  if (!Array.isArray(audit.categories)) throw new Error("categories missing");
  const ids = audit.categories.map((c) => c.id);
  for (const id of REQUIRED_IDS)
    if (!ids.includes(id)) throw new Error(`Missing category: ${id}`);
  audit.overallScore = clamp(audit.overallScore || 0);
  return audit;
}

// ── Routes ──────────────────────────────────────────────────────────────────
app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    publicEngine: "heuristic",
    publicScanLimitPerDay: PUBLIC_SCAN_LIMIT,
    internalEngine: ANTHROPIC_API_KEY ? `claude (${ANTHROPIC_MODEL})` : "heuristic",
    internalApi: INTERNAL_API_KEY ? "configured" : "disabled",
  });
});

app.get("/config", (_req, res) => {
  res.json({ version: CONFIG.version, aiCrawlers: AI_CRAWLERS, categoryWeights: CATEGORY_WEIGHTS, schemaTypes: CONFIG.schemaTypes });
});

// ── Shared audit pipeline ───────────────────────────────────────────────────
// Scrape + /llms.txt + /robots.txt in parallel, then audit. The PUBLIC tool runs
// the fast, free heuristic engine; the internal API (Pulsec) opts into Claude via
// { useClaude: true }. Throws on bad input (err.status = 400) or runtime failure.
async function runVisibilityAudit(rawUrl, { useClaude = false } = {}) {
  const target = normalizeUrl(rawUrl); // throws (status 400) on missing/invalid URL
  const started = Date.now();

  const [scrape, llms, robots] = await Promise.all([
    scrapeUrl(target.href),
    checkLlmsTxt(target.origin),
    checkRobots(target.origin),
  ]);

  const auditInput = { url: target.href, host: target.host, scrape, llms, robots };

  let audit;
  let engine = "heuristic";
  if (useClaude && ANTHROPIC_API_KEY) {
    try {
      audit = ensureSchema(await callClaude(auditInput));
      engine = "claude";
    } catch (e) {
      console.warn("[audit] Claude failed, falling back to heuristic:", e.message);
      audit = heuristicAudit({ scrape, llms, robots, host: target.host });
    }
  } else {
    audit = heuristicAudit({ scrape, llms, robots, host: target.host });
  }

  audit.engine = engine;
  audit.meta = {
    url: target.href,
    host: target.host,
    scannedAt: new Date().toISOString(),
    durationMs: Date.now() - started,
    signals: {
      llmsTxt: llms.exists,
      robotsTxt: robots.exists,
      aiBotsAllowed: robots.aiBotsAllowed || [],
      jsonLdCount: scrape.jsonLdCount,
      schemaTypes: scrape.schemaTypes,
      wordCount: scrape.wordCount,
      hreflangCount: scrape.hreflangCount,
    },
  };
  return audit;
}

// Constant-time comparison of the internal shared secret (avoids timing attacks).
function internalKeyMatches(provided) {
  if (!INTERNAL_API_KEY || !provided) return false;
  const a = Buffer.from(String(provided));
  const b = Buffer.from(INTERNAL_API_KEY);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

// ── Per-IP daily rate limit for the public tool (in-memory, resets at UTC day).
const scanHits = new Map(); // ip -> { day: "YYYY-MM-DD", count }
function consumePublicScan(ip) {
  const day = new Date().toISOString().slice(0, 10);
  const rec = scanHits.get(ip);
  if (!rec || rec.day !== day) {
    scanHits.set(ip, { day, count: 1 });
    return { ok: true, remaining: PUBLIC_SCAN_LIMIT - 1 };
  }
  if (rec.count >= PUBLIC_SCAN_LIMIT) return { ok: false, remaining: 0 };
  rec.count += 1;
  return { ok: true, remaining: PUBLIC_SCAN_LIMIT - rec.count };
}

// Public audit route — GeoPageScan frontend. Heuristic engine (free, fast),
// limited to PUBLIC_SCAN_LIMIT scans per IP per day.
app.post("/audit", async (req, res) => {
  // validate URL first so a bad request never burns a daily scan
  let target;
  try {
    target = normalizeUrl(req.body?.url);
  } catch (e) {
    return res.status(e.status || 400).json({ error: e.message || "URL is required" });
  }

  const ip = req.ip || (req.headers["x-forwarded-for"] || "").split(",")[0].trim() || "unknown";
  const rl = consumePublicScan(ip);
  if (!rl.ok) {
    return res.status(429).json({
      error: "Daily limit reached",
      message: `You've used all ${PUBLIC_SCAN_LIMIT} free scans for today. Please come back tomorrow — or contact us about higher-volume access.`,
      limit: PUBLIC_SCAN_LIMIT,
    });
  }

  try {
    const audit = await runVisibilityAudit(target.href); // heuristic (free, fast)
    audit.meta.scansRemaining = rl.remaining;
    audit.meta.scanLimit = PUBLIC_SCAN_LIMIT;
    res.json(audit);
  } catch (e) {
    console.error("[audit] error:", e.message);
    res.status(e.status || 500).json({ error: e.message || "Audit failed" });
  }
});

// Internal server-to-server API (e.g. Pulsec). Claude-powered, no rate limit,
// protected by a shared secret in the X-Internal-Key header (401 if missing/wrong).
app.post("/api/internal/visibility-scan", async (req, res) => {
  if (!internalKeyMatches(req.get("X-Internal-Key"))) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  try {
    res.json(await runVisibilityAudit(req.body?.url, { useClaude: true }));
  } catch (e) {
    console.error("[internal-scan] error:", e.message);
    res.status(e.status || 500).json({ error: e.message || "Audit failed" });
  }
});

app.listen(PORT, () => {
  console.log(`GeoPageScan backend running on http://localhost:${PORT}`);
  console.log(`Audit engine: ${ANTHROPIC_API_KEY ? `Claude (${ANTHROPIC_MODEL})` : "heuristic (no API key — fully functional)"}`);
});
